name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download IP list
        run: wget -O ip.txt https://www.cloudflare-cn.com/ips-v4/#

      - name: Make script executable
        run: chmod +x CloudflareST

      - name: Run script
        run: ./CloudflareST

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update IP list" || echo "No changes to commit"
          git push origin HEAD:main
